name: coolambient
favicon: null
layout_spectrum: 0.23950246744789183
typography_spectrum: 0.17114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#365d79'
    - '#6c9bbc'
    - '#e3e4e4'
    - '#adafae'
  brandStrength: 0.8740602710749954
  lightness: 0.7457540465984493
  saturation: 0.20185396983288229
  rhythmicContrast: 0.48985349852591753
purpose: []
